export interface form{
    
        addChangeDeleteFlag: any,
        btnCndAdd: any,
        btnCndCopy: any,
        btnCndDelete: any,
        btnCndModify: any,
        btnCndRenumber: any,
        btnCndView: any,
        btnCndViewDetail:any,
        btnLblAdd: any,
        btnLblCopy: any,
        btnLblDelete: any,
        btnLblModify: any,
        btnLblRenumber: any,
        btnLblView: any,
        btnLblViewDetail: any,
        btnResAdd: any,
        btnResCopy: any,
        btnResDelete: any,
        btnResModify: any,
        btnResRenumber: any,
        btnResView: any,
        btnResViewDetail: any,
        comment: any,
        condition: any,
        helpText: any,
        hidden: any,
        hidePremium: any,
        formType:any,
        scriptBefore:any,
        scriptAfter:any,
        maxOccurs: any,
        minOccurs: any,
        name: any,
        number: any,
        ratebookId: any,
        sequence: any,
        subSequence: any,
        tabCondition: null,
        tabResourceName: null,
        tableId: any,
        templateFile: any,
        type: any,
        id:any
      
}